AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
  check2FaTokenFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'check2FaToken'
      Handler: check2FaTokenFunc/index.handler
      Layers:
        - arn:aws:lambda:us-east-1:340215726071:layer:twilioNodeLibrary:2
      Runtime: nodejs12.x
      Description: 'Twilio Lookup phone number'
      MemorySize: 128
      Timeout: 15
  lookupPhoneNumberFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'lookupPhoneNumber'
      Handler: lookupPhoneNumberFunc/index.handler
      Layers:
        - arn:aws:lambda:us-east-1:340215726071:layer:twilioNodeLibrary:2
      Runtime: nodejs12.x
      Description: 'Twilio Lookup phone number'
      MemorySize: 128
      Timeout: 15
